/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        /** Usunięcie planu (miękkie) */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateItem"];
        post?: never;
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/days/{dayId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["renameDay"];
        post?: never;
        delete: operations["deleteDay"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/days/{dayId}/items/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Nowa kolejność ćwiczeń w dniu (pełna lista id) */
        put: operations["reorderItems"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/days/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Nowa kolejność dni (pełna lista id) */
        put: operations["reorderDays"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Szczegóły ćwiczenia; dla autora własnego ćwiczenia także powiązany sprzęt (equipmentIds) */
        get: operations["get_1"];
        /** Edycja własnego ćwiczenia (tylko autor); 409 exercise_used_by_others przy próbie ukrycia ćwiczenia używanego w cudzych planach */
        put: operations["update_1"];
        post?: never;
        /** Usunięcie własnego ćwiczenia (ukrywa z list; plany i historia zostają) */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        /** Edycja sprzętu (członkowie siłowni); zmiana statusu na REMOVED_FROM_GYM też tutaj */
        put: operations["update_2"];
        post?: never;
        /** Usunięcie sprzętu (miękkie) */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/{equipmentId}/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Powiązanie sprzętu z ćwiczeniem (idempotentne, członkowie) */
        put: operations["link"];
        post?: never;
        delete: operations["unlink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historia zakończonych treningów (od najnowszych) */
        get: operations["history"];
        put?: never;
        /** Start treningu z dnia planu lub ad hoc; 409 session_already_active (activeSessionId) */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zakończenie i zapis treningu do historii */
        post: operations["finish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dodanie ćwiczenia do treningu (dostępnego w siłowni) */
        post: operations["addExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/exercises/{sessionExerciseId}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dodatkowa seria */
        post: operations["addSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Porzucenie treningu (nie trafia do historii) */
        post: operations["abandon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oznaczenie zgłoszenia jako rozwiązanego (członkowie siłowni) */
        post: operations["resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Moje plany (aktywne lub zarchiwizowane), opcjonalnie dla siłowni */
        get: operations["list"];
        put?: never;
        /** Nowy plan w siłowni, do której należę */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unarchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/items/{itemId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Przesunięcie ćwiczenia o jedną pozycję w dniu (przyciski góra/dół) */
        post: operations["moveItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/days/{dayId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Przesunięcie dnia o jedną pozycję (przyciski góra/dół) */
        post: operations["moveDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/days/{dayId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dodanie ćwiczenia do dnia – tylko ćwiczenia dostępne na sprzęcie siłowni planu (422 exercise_not_available) */
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["copy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zmiana hasła – unieważnia pozostałe sesje i zwraca nowe tokeny */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wyszukiwanie siłowni po nazwie i mieście */
        get: operations["search"];
        put?: never;
        /** Dodanie siłowni. 409 gym_possible_duplicate (z listą candidates), jeśli istnieje podobna – ponów z confirmDuplicate=true */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dołączenie do siłowni (idempotentne) */
        post: operations["join"];
        delete: operations["leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Własne ćwiczenie w siłowni (tylko członkowie); domyślnie prywatne */
        post: operations["createCustom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sprzęt w siłowni – wyszukiwanie po nazwie, filtr kategorii i statusu */
        get: operations["list_1"];
        put?: never;
        /** Dodanie sprzętu (tylko członkowie siłowni) */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/{id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zgłoszenia problemów (otwarte najpierw) */
        get: operations["reports"];
        put?: never;
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/{id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dodanie/zmiana zdjęcia (jpg/png/webp, max 5 MB) */
        post: operations["uploadPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rejestracja nowego konta (loguje od razu) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nowy access token na podstawie refresh tokenu z ciasteczka (rotacja) */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Żądanie resetu hasła (w MVP link jest logowany w konsoli backendu) */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/sets/{setId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeSet"];
        options?: never;
        head?: never;
        /** Zapis serii: powtórzenia, ciężar, odhaczenie */
        patch: operations["updateSet"];
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trwający trening (204, jeśli brak) */
        get: operations["active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Moje siłownie */
        get: operations["myGyms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/exercises/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Widoczne ćwiczenia o podobnej nazwie (podpowiedź przy dodawaniu) */
        get: operations["similar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/exercises/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ćwiczenia możliwe do wykonania na sprzęcie siłowni (+ z masą ciała) wraz ze sprzętem */
        get: operations["available"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/equipment/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sprzęt o podobnej nazwie w siłowni (ograniczanie duplikatów) */
        get: operations["similar_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Siłownie o podobnej nazwie w danym mieście (ostrzeżenie o duplikacie) */
        get: operations["similar_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["original"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["thumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Biblioteka ćwiczeń: globalne + widoczne własne ćwiczenia moich siłowni (albo tylko siłowni gymId) */
        get: operations["library"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exerciseId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ostatnie wyniki ćwiczenia z zakończonych treningów */
        get: operations["exerciseHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historia zmian sprzętu (od najnowszych) */
        get: operations["history_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/{equipmentId}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ćwiczenia na danym sprzęcie (dopasowanie po typie lub jawne powiązanie) */
        get: operations["forEquipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Słownik typów sprzętu */
        get: operations["types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/exercises/{sessionExerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeExercise"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdatePlanRequest: {
            name: string;
            description?: string;
        };
        PlanDayDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            position: number;
            items: components["schemas"]["PlanItemDto"][];
        };
        PlanDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            /** Format: uuid */
            gymId: string;
            gymName: string;
            archived: boolean;
            /** @enum {string} */
            visibility: "PRIVATE" | "GYM_OFFICIAL";
            days: components["schemas"]["PlanDayDto"][];
            /** Format: int32 */
            warningCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PlanEquipmentDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            status: "ACTIVE" | "REMOVED_FROM_GYM";
            deleted: boolean;
            thumbnailUrl?: string;
            photoUrl?: string;
        };
        PlanExerciseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            primaryMuscle: "CHEST" | "BACK" | "LOWER_BACK" | "TRAPS" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "GLUTES" | "QUADRICEPS" | "HAMSTRINGS" | "ADDUCTORS" | "ABDUCTORS" | "CALVES" | "FULL_BODY" | "CARDIO";
            bodyweight: boolean;
        };
        PlanItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            position: number;
            exercise: components["schemas"]["PlanExerciseDto"];
            equipment?: components["schemas"]["PlanEquipmentDto"];
            /** Format: int32 */
            sets: number;
            /** Format: int32 */
            repsMin: number;
            /** Format: int32 */
            repsMax: number;
            targetWeightKg?: number;
            /** Format: int32 */
            restSeconds: number;
            note?: string;
            equipmentUnavailable: boolean;
        };
        PlanItemRequest: {
            /** Format: uuid */
            exerciseId: string;
            /** Format: uuid */
            equipmentId?: string;
            /** Format: int32 */
            sets?: number;
            /** Format: int32 */
            repsMin?: number;
            /** Format: int32 */
            repsMax?: number;
            targetWeightKg?: number;
            /** Format: int32 */
            restSeconds?: number;
            note?: string;
        };
        PlanDayRequest: {
            name: string;
        };
        ReorderRequest: {
            ids: string[];
        };
        CreateExerciseRequest: {
            name: string;
            /** @enum {string} */
            primaryMuscle: "CHEST" | "BACK" | "LOWER_BACK" | "TRAPS" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "GLUTES" | "QUADRICEPS" | "HAMSTRINGS" | "ADDUCTORS" | "ABDUCTORS" | "CALVES" | "FULL_BODY" | "CARDIO";
            secondaryMuscles?: ("CHEST" | "BACK" | "LOWER_BACK" | "TRAPS" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "GLUTES" | "QUADRICEPS" | "HAMSTRINGS" | "ADDUCTORS" | "ABDUCTORS" | "CALVES" | "FULL_BODY" | "CARDIO")[];
            description?: string;
            bodyweight?: boolean;
            equipmentIds?: string[];
            /** @enum {string} */
            visibility?: "PRIVATE" | "GYM";
        };
        EquipmentTypeDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** @enum {string} */
            category: "STRENGTH_MACHINE" | "CABLE" | "FREE_WEIGHTS" | "BENCH" | "CARDIO" | "FUNCTIONAL" | "OTHER";
        };
        ExerciseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            primaryMuscle: "CHEST" | "BACK" | "LOWER_BACK" | "TRAPS" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "GLUTES" | "QUADRICEPS" | "HAMSTRINGS" | "ADDUCTORS" | "ABDUCTORS" | "CALVES" | "FULL_BODY" | "CARDIO";
            secondaryMuscles: ("CHEST" | "BACK" | "LOWER_BACK" | "TRAPS" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "GLUTES" | "QUADRICEPS" | "HAMSTRINGS" | "ADDUCTORS" | "ABDUCTORS" | "CALVES" | "FULL_BODY" | "CARDIO")[];
            description?: string;
            bodyweight: boolean;
            /** @enum {string} */
            scope: "GLOBAL" | "CUSTOM";
            /** @enum {string} */
            visibility?: "PRIVATE" | "GYM";
            mine: boolean;
            /** Format: uuid */
            gymId?: string;
            equipmentTypes: components["schemas"]["EquipmentTypeDto"][];
            equipmentIds?: (string | null)[];
            createdBy?: components["schemas"]["UserRefDto"];
        };
        UserRefDto: {
            /** Format: uuid */
            id: string;
            displayName: string;
        };
        UpdateEquipmentRequest: {
            name: string;
            /** @enum {string} */
            category: "STRENGTH_MACHINE" | "CABLE" | "FREE_WEIGHTS" | "BENCH" | "CARDIO" | "FUNCTIONAL" | "OTHER";
            /** Format: uuid */
            equipmentTypeId?: string;
            description?: string;
            /** Format: int32 */
            quantity?: number;
            /** @enum {string} */
            status: "ACTIVE" | "REMOVED_FROM_GYM";
            /** Format: int64 */
            version: number;
        };
        EquipmentDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gymId: string;
            gymName: string;
            name: string;
            /** @enum {string} */
            category: "STRENGTH_MACHINE" | "CABLE" | "FREE_WEIGHTS" | "BENCH" | "CARDIO" | "FUNCTIONAL" | "OTHER";
            equipmentType?: components["schemas"]["EquipmentTypeDto"];
            description?: string;
            /** Format: int32 */
            quantity?: number;
            /** @enum {string} */
            status: "ACTIVE" | "REMOVED_FROM_GYM";
            /** @enum {string} */
            source: "COMMUNITY" | "GYM_OFFICIAL";
            verified: boolean;
            photoUrl?: string;
            thumbnailUrl?: string;
            createdBy: components["schemas"]["UserRefDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
            /** Format: int64 */
            openReportCount: number;
            member: boolean;
        };
        StartSessionRequest: {
            /** Format: uuid */
            planId?: string;
            /** Format: uuid */
            planDayId?: string;
            /** Format: uuid */
            gymId?: string;
        };
        ExerciseHistoryEntryDto: {
            /** Format: uuid */
            sessionId: string;
            sessionTitle: string;
            /** Format: date-time */
            date: string;
            sets: components["schemas"]["SetResultDto"][];
        };
        SessionDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: uuid */
            gymId: string;
            gymName: string;
            /** Format: uuid */
            planId?: string;
            /** @enum {string} */
            status: "IN_PROGRESS" | "FINISHED" | "ABANDONED";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
            note?: string;
            exercises: components["schemas"]["SessionExerciseDto"][];
        };
        SessionExerciseDto: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            position: number;
            exercise: components["schemas"]["PlanExerciseDto"];
            equipment?: components["schemas"]["PlanEquipmentDto"];
            /** Format: int32 */
            targetRepsMin?: number;
            /** Format: int32 */
            targetRepsMax?: number;
            targetWeightKg?: number;
            /** Format: int32 */
            restSeconds: number;
            note?: string;
            sets: components["schemas"]["SessionSetDto"][];
            previous?: components["schemas"]["ExerciseHistoryEntryDto"];
        };
        SessionSetDto: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            setNumber: number;
            /** Format: int32 */
            reps?: number;
            weightKg?: number;
            completed: boolean;
        };
        SetResultDto: {
            /** Format: int32 */
            setNumber: number;
            /** Format: int32 */
            reps?: number;
            weightKg?: number;
        };
        FinishSessionRequest: {
            note?: string;
        };
        AddSessionExerciseRequest: {
            /** Format: uuid */
            exerciseId: string;
            /** Format: uuid */
            equipmentId?: string;
            /** Format: int32 */
            sets?: number;
            /** Format: int32 */
            restSeconds?: number;
        };
        EquipmentRefDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        EquipmentReportDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            equipmentId: string;
            /** @enum {string} */
            type: "DUPLICATE" | "WRONG_DATA" | "REMOVED_FROM_GYM";
            comment?: string;
            duplicateOf?: components["schemas"]["EquipmentRefDto"];
            /** @enum {string} */
            status: "OPEN" | "RESOLVED";
            reporter: components["schemas"]["UserRefDto"];
            /** Format: date-time */
            createdAt: string;
            resolvedBy?: components["schemas"]["UserRefDto"];
            /** Format: date-time */
            resolvedAt?: string;
        };
        CreatePlanRequest: {
            /** Format: uuid */
            gymId: string;
            name: string;
            description?: string;
        };
        CopyPlanRequest: {
            name?: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        AuthResponse: {
            accessToken: string;
            /** Format: int64 */
            expiresIn: number;
            user: components["schemas"]["UserDto"];
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: string;
            /** @enum {string} */
            role: "USER" | "GYM_ADMIN" | "TRAINER";
            /** Format: date-time */
            createdAt: string;
        };
        CreateGymRequest: {
            name: string;
            city: string;
            address: string;
            description?: string;
            confirmDuplicate?: boolean;
        };
        GymDto: {
            /** Format: uuid */
            id: string;
            name: string;
            city: string;
            address: string;
            description?: string;
            /** @enum {string} */
            status: "COMMUNITY" | "VERIFIED";
            /** Format: int64 */
            memberCount: number;
            member: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateEquipmentRequest: {
            name: string;
            /** @enum {string} */
            category: "STRENGTH_MACHINE" | "CABLE" | "FREE_WEIGHTS" | "BENCH" | "CARDIO" | "FUNCTIONAL" | "OTHER";
            /** Format: uuid */
            equipmentTypeId?: string;
            description?: string;
            /** Format: int32 */
            quantity?: number;
        };
        CreateReportRequest: {
            /** @enum {string} */
            type: "DUPLICATE" | "WRONG_DATA" | "REMOVED_FROM_GYM";
            comment?: string;
            /** Format: uuid */
            duplicateOfId?: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirmRequest: {
            token: string;
            newPassword: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        UpdateSetRequest: {
            /** Format: int32 */
            reps?: number;
            weightKg?: number;
            completed?: boolean;
        };
        UpdateProfileRequest: {
            displayName: string;
        };
        PageResponseSessionSummaryDto: {
            content: components["schemas"]["SessionSummaryDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        SessionSummaryDto: {
            /** Format: uuid */
            id: string;
            title: string;
            gymName: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string;
            /** Format: int32 */
            exerciseCount: number;
            /** Format: int32 */
            completedSets: number;
            volumeKg: number;
        };
        PlanSummaryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            gymId: string;
            gymName: string;
            archived: boolean;
            /** Format: int32 */
            dayCount: number;
            /** Format: int32 */
            exerciseCount: number;
            /** Format: int32 */
            warningCount: number;
            /** Format: date-time */
            updatedAt: string;
        };
        GymSummaryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            city: string;
            address: string;
            /** @enum {string} */
            status: "COMMUNITY" | "VERIFIED";
            /** Format: int64 */
            memberCount: number;
            member: boolean;
        };
        PageResponseGymSummaryDto: {
            content: components["schemas"]["GymSummaryDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        AvailableExerciseDto: {
            exercise: components["schemas"]["ExerciseDto"];
            equipment: components["schemas"]["EquipmentOptionDto"][];
        };
        EquipmentOptionDto: {
            /** Format: uuid */
            id: string;
            name: string;
            thumbnailUrl?: string;
        };
        EquipmentSummaryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            category: "STRENGTH_MACHINE" | "CABLE" | "FREE_WEIGHTS" | "BENCH" | "CARDIO" | "FUNCTIONAL" | "OTHER";
            equipmentType?: components["schemas"]["EquipmentTypeDto"];
            /** Format: int32 */
            quantity?: number;
            /** @enum {string} */
            status: "ACTIVE" | "REMOVED_FROM_GYM";
            thumbnailUrl?: string;
            /** Format: int64 */
            openReportCount: number;
        };
        PageResponseEquipmentSummaryDto: {
            content: components["schemas"]["EquipmentSummaryDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        EquipmentChangeDto: {
            /** Format: uuid */
            id: string;
            user: components["schemas"]["UserRefDto"];
            /** Format: date-time */
            changedAt: string;
            /** @enum {string} */
            changeType: "CREATED" | "UPDATED" | "STATUS_CHANGED" | "PHOTO_CHANGED" | "DELETED";
            changes: {
                [key: string]: components["schemas"]["FieldChange"];
            };
        };
        FieldChange: {
            oldValue?: string;
            newValue?: string;
        };
        PageResponseEquipmentChangeDto: {
            content: components["schemas"]["EquipmentChangeDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        EquipmentExerciseDto: {
            exercise: components["schemas"]["ExerciseDto"];
            linked: boolean;
            byType: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    renameDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDayRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    deleteDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    reorderItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    reorderDays: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDto"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExerciseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDto"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentDto"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEquipmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentDto"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipmentId: string;
                exerciseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unlink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipmentId: string;
                exerciseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    history: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseSessionSummaryDto"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    finish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FinishSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    addExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSessionExerciseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    addSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                sessionExerciseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    abandon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentReportDto"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                archived?: boolean;
                gymId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummaryDto"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    unarchive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    moveItem: {
        parameters: {
            query: {
                direction: "UP" | "DOWN";
            };
            header?: never;
            path: {
                planId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    addDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDayRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    moveDay: {
        parameters: {
            query: {
                direction: "UP" | "DOWN";
            };
            header?: never;
            path: {
                planId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanItemRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    copy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CopyPlanRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                q?: string;
                city?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseGymSummaryDto"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGymRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymDto"];
                };
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCustom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExerciseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDto"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                q?: string;
                category?: "STRENGTH_MACHINE" | "CABLE" | "FREE_WEIGHTS" | "BENCH" | "CARDIO" | "FUNCTIONAL" | "OTHER";
                status?: "ACTIVE" | "REMOVED_FROM_GYM";
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseEquipmentSummaryDto"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEquipmentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentDto"];
                };
            };
        };
    };
    reports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentReportDto"][];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentReportDto"];
                };
            };
        };
    };
    uploadPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentDto"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    removeSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                setId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    updateSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                setId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    active: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    myGyms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymSummaryDto"][];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymDto"];
                };
            };
        };
    };
    similar: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDto"][];
                };
            };
        };
    };
    available: {
        parameters: {
            query?: {
                q?: string;
                muscle?: "CHEST" | "BACK" | "LOWER_BACK" | "TRAPS" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "GLUTES" | "QUADRICEPS" | "HAMSTRINGS" | "ADDUCTORS" | "ABDUCTORS" | "CALVES" | "FULL_BODY" | "CARDIO";
            };
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableExerciseDto"][];
                };
            };
        };
    };
    similar_1: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentSummaryDto"][];
                };
            };
        };
    };
    similar_2: {
        parameters: {
            query: {
                name: string;
                city: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymSummaryDto"][];
                };
            };
        };
    };
    original: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    thumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    library: {
        parameters: {
            query?: {
                gymId?: string;
                q?: string;
                muscle?: "CHEST" | "BACK" | "LOWER_BACK" | "TRAPS" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "GLUTES" | "QUADRICEPS" | "HAMSTRINGS" | "ADDUCTORS" | "ABDUCTORS" | "CALVES" | "FULL_BODY" | "CARDIO";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDto"][];
                };
            };
        };
    };
    exerciseHistory: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                exerciseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseHistoryEntryDto"][];
                };
            };
        };
    };
    history_1: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseEquipmentChangeDto"];
                };
            };
        };
    };
    forEquipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentExerciseDto"][];
                };
            };
        };
    };
    types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentTypeDto"][];
                };
            };
        };
    };
    removeExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                sessionExerciseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
}
